version: "3"

services:
  app:
    container_name: dev_svelte_template_php
    build:
      context: .
      dockerfile: Dockerfile.local
    user: "node:node"
    # command: npm run dev -- --port 8080 --host 0.0.0.0
    environment:
      NODE_ENV: "development"
    volumes:
      - ./app:/var/www/app
      - dev_svelte_template_node_module_volume:/var/www/app/node_modules
    working_dir: "/var/www/app"
    ports:
      - "8080:8080"
    tty: true
    networks:
      - dev_svelte_template_network

volumes:
  dev_svelte_template_node_module_volume:
networks:
  dev_svelte_template_network:
