version: "3"

services:
  app:
    container_name: dev_svelte_template_php
    build: .
    user: "node:node"
    environment:
      NODE_ENV: "development"
    volumes:
      - ./:/usr/src/app
    working_dir: "/usr/src/app"
    ports:
      - "4200:4200"
    tty: true
    networks:
      - dev_svelte_template_network

networks:
  dev_svelte_template_network:
