FROM node:18.16-alpine

ENV APP_ROOT /var/www/app

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh

RUN mkdir -p $APP_ROOT/node_modules/ && \
    chmod -R 777 $APP_ROOT/node_modules/

WORKDIR $APP_ROOT

# COPY package.json package-lock.json $APP_ROOT/
# RUN npm install

CMD ["bash"]
